{% set name = "opentelemetry-exporter-opencensus" %}
{% set version = "0.55b1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_opencensus-{{ version }}.tar.gz
  sha256: 0ee7811dcffe387e314cd5dc91e4cb33598dbdf43834cb4e96cc14a4d889ddb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - grpcio <2.0.0,>=1.66.2
    - opencensus-proto <1.0.0,>=0.1.0
    - opentelemetry-api >=1.34.1
    - opentelemetry-sdk >=1.15
    - protobuf ~=3.13
    - setuptools >=16.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    #- pip check
    # opentelemetry-exporter-opencensus 0.52b1 has requirement protobuf~=3.13, but you have protobuf 5.29.3 version 3.13 and version 3.14 are 4 years old - from 2021
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-opencensus
  summary: OpenCensus Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
